import Head from "next/head";
import Image from "next/image";
import Header from "../components/section1/Header";
import Section from "../components/section1/Section";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Section />
      
    </div>
  );
}
